name: uptodate
description: Keep your repo 'uptodate' by creating issues if a dependency updates.
version: 0.6.0
repository: https://github.com/fischerscode/uptodate

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  http: ^0.13.4
  version: ^2.0.0
  yaml: ^3.1.0
  yamltools: ^1.1.1

dev_dependencies:
  build_runner: ^2.1.5
  mockito: ^5.0.16
  lints: ^1.0.1
  test: ^1.19.3
